### ISSUE TITLE
planning for java compile and java judge

### ISSUE THREAD

**Issue by mahmoudKheyrati** [mahmoudKheyrati/Judge#3]
- [x] 1. **java compile 
- [x] 2. java judge**
- [x] 3.

**Comment by mollaeemohammad** [comment]
java compile is seperated from compileC and runJavaFile is written as runExeFile
and for java judge just I should change the name of cFileName and cFilePath to file fileName and filePath which is done
example of them and their own will be pushed afternoon

**Comment by mahmoudKheyrati** [comment]
> java compile is seperated from compileC and runJavaFile is written as runExeFile
> and for java judge just I should change the name of cFileName and cFilePath to file fileName and filePath which is done
> example of them and their own will be pushed afternoon

runJavaFile as a runExeFile ? what ? **java compiled file isn't .exe but it is .jar file** and you can run it with `java -jar filename.jar`
